name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "30 21 * * *"   # runs daily at 03:00 IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contributions
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: praveenbhardwaj

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "update: 3D contribution graph"; then
            git push
          else
            echo "no changes"
          fi